feat(pingpong): add
PoolC/Gagkobot pull request #1
Opened 2021-01-09 15:02 UTC by ippnsj

feature pingpong add

2021-01-09 15:03 UTC, Jjungs7 commented
pull request할 때 무슨 기능을 만들었는지 간단하게 적어주세요. 제목은 구현한 기능을 요약해야됩니다.

2021-01-09 15:04 UTC, Jjungs7 commented on .gitignore
> +.ipynb_checkpoints/
[.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) 여기 가면 python gitignore가 있으니까 이걸로 대체하고, 추가적으로 ignore할 필요가 있다면 파일에 적어줍니다

2021-01-09 15:05 UTC, Jjungs7 commented on gagkobot.py
> +# In[16]:
이런 주석은 파일 가독성을 떨어뜨립니다. commit할땐 주석을 **모두** 삭제해주세요. 나중에 쓸 것 같아서 남겨놓은 코드도 모두 삭제합니다

2021-01-09 15:29 UTC, Jjungs7 requested changes

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +#!/usr/bin/env python
이런 주석은 파일 가독성을 떨어뜨립니다. commit할땐 주석을 **모두** 삭제해주세요. 나중에 쓸 것 같아서 남겨놓은 코드도 모두 삭제합니다

2021-01-09 15:29 UTC, Jjungs7 commented on .gitignore
> +.ipynb_checkpoints/
[.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) 여기 가면 python gitignore가 있으니까 이걸로 대체하고, 추가적으로 ignore할 파일이 있다면 따로 적어줍니다

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +import os
[pylint](https://code.visualstudio.com/docs/python/linting)를 기준으로 코드를 refactoring 해주세요.

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +from slacker import Slacker
[import](https://www.python.org/dev/peps/pep-0008/#imports) 순서를 지켜주세요.

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +print(token)
logging을 위한 출력을 제외하고는 print를 모두 삭제해주세요

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +    answer = get_answer(user_query)
적절한 new line은 코드 가독성을 높입니다

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +        return make_response("ok", 200, )
마지막 comma는 의도된건가요?

2021-01-09 15:29 UTC, Jjungs7 commented on gagkobot.py
> +    app.run(debug=True)
os.getenv를 활용하여 dev 환경일때는 debug를, production 환경일때는 debug하지 않게 수정해봅시다

2021-01-12 01:35 UTC, Jjungs7 commented on gagkobot.py
> +        return make_response(message, 200, {"X-Slack-No-Retry": 1})
- 적절한 new line은 코드 가독성을 높입니다
- 51줄에 마지막 콤마는 의도된건가요?

```suggestion
def event_handler(event_type, slack_event):
    channel = slack_event["event"]["channel"]
    user_query = slack_event['event']['text'].strip()

    answer = get_answer(user_query)
    if answer != "":
        slack.chat.post_message(channel, answer)
        return make_response("ok", 200, )
    else:
        message = "[%s] cannot find event handler" % event_type
        return make_response(message, 200, {"X-Slack-No-Retry": 1})
```

2021-01-12 01:36 UTC, Jjungs7 commented on .gitignore
> +.ipynb_checkpoints/
[.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) 여기 가면 python gitignore가 있으니까 이걸로 대체한 다음 추가적으로 무시할 필요가 있는 파일도 적어줍니다

2021-01-12 01:43 UTC, Jjungs7 commented on gagkobot.py
> +import os
[PEP-8#Imports](https://www.python.org/dev/peps/pep-0008/#imports)에 의거하여 import 순서를 지켜주세요.

2021-01-15 09:54 UTC, yoonseokch commented
대단하십니다

2021-02-14 07:49 UTC, Jjungs7 requested changes

2021-02-14 07:49 UTC, Jjungs7 commented on .gitignore
> +*.json
python 플젝인데 node_modules와 *.json이 추가된 이유가 있나요?

2021-02-14 07:54 UTC, Jjungs7 commented
README.md 나 requirements.txt(관례적으로 쓰이는 이름, node에서의 package.json 와 같은 파일)와 같은 안내사항이 없어서 실행을 못 하고 있네요 ㅠㅠ 실행에 애먹는 팀원을 위해 관련 정보를 올려주시면 어떨까요?

<img width="914" alt="Screen Shot 2021-02-14 at 4 48 40 PM" src="https://user-images.githubusercontent.com/14287915/107871454-12fbf380-6ee5-11eb-9f76-4de2ce2910cd.png">

2021-02-14 08:01 UTC, Jjungs7 commented on gagkobot.py
> +    app.run(debug=debug)
[pep 8 - W292](https://pep8.readthedocs.io/en/release-1.7.x/intro.html) 에 의하면 파일 마지막에 new line으로 끝나야하는데 그렇지 않네요. 이는 커밋으로 강제하진 않겠고 pycharm이나 linter를 사용하면 쉽게 해결할 수 있다는 거 참고부탁드려요

2021-02-14 08:02 UTC, yoonseokch commented on gagkobot.py
> +    app.run(debug=debug)
아하 vs code에서 pylint를 적용했는데 설정이 잘못되었나보네요 확인해보겠습니다

2021-02-21 06:48 UTC, Jjungs7 approved these changes

2021-02-21 06:49 UTC, merged